CREATE TABLE "room"
  ("id"        SERIAL PRIMARY KEY NOT NULL,
   "name"      TEXT,
   "public"    BOOLEAN DEFAULT FALSE NOT NULL,
   "created"   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL);

